#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.add_source_files(env.servers_sources, "*.cpp")

env_fidelityfx = env.Clone()
env_fidelityfx.disable_warnings()
env_fidelityfx.Prepend(CPPPATH=[
    "#thirdparty/FidelityFX/sdk/include",
    "#thirdparty/FidelityFX/sdk/src/shared",
    "#thirdparty/FidelityFX/sdk/src/backends/shared",
    "#thirdparty/FidelityFX/sdk/src/backends/shared/blob_accessors",
    "#thirdparty/FidelityFX/sdk/src/components",
    "#thirdparty/FidelityFX/sdk/src/components/brixelizer",
    "#thirdparty/FidelityFX/sdk/src/backends/vk/shaders/ffx_sc_out",
    "#thirdparty/volk",
])
env.Prepend(CPPPATH=[
    "#thirdparty/FidelityFX/sdk/include",
    "#thirdparty/FidelityFX/sdk/src/shared",
    "#thirdparty/FidelityFX/sdk/src/backends/vk/shaders/ffx_sc_out",
    "#thirdparty/volk",
])
env_fidelityfx.Append(CPPDEFINES=["FFX_GCC", "FFX_BRIXELIZER", "FFX_BRIXELIZER_SHADER_BLOBS"])
env_fidelityfx.Append(CPPFLAGS=["-include", "servers/rendering/renderer_rd/ffx_compat.h"])

thirdparty_dir = "#thirdparty/FidelityFX/sdk/"
thirdparty_sources = [
    "src/components/brixelizer/ffx_brixelizer.cpp",
    "src/components/brixelizer/ffx_brixelizer_raw.cpp",
    "src/backends/shared/ffx_shader_blobs.cpp",
    "src/backends/shared/blob_accessors/ffx_brixelizer_shaderblobs.cpp",
    "src/backends/vk/ffx_vk.cpp",
    "src/shared/ffx_assert.cpp",
    "src/shared/ffx_message.cpp",
    "src/shared/ffx_object_management.cpp",
    "src/shared/ffx_breadcrumbs_list.cpp",
]
thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

thirdparty_obj = []
env_fidelityfx.add_source_files(thirdparty_obj, thirdparty_sources)
env.servers_sources += thirdparty_obj

SConscript("effects/SCsub")
SConscript("environment/SCsub")
SConscript("forward_clustered/SCsub")
SConscript("forward_mobile/SCsub")
SConscript("shaders/SCsub")
SConscript("spirv-reflect/SCsub")
SConscript("storage_rd/SCsub")
