#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env_env = env.Clone()
env_env.Prepend(CPPPATH=["#thirdparty/amd-brixelizer/"])
env_env.add_source_files(env.servers_sources, "*.cpp")
